# -*- coding: utf-8 -*-
"""compiler.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mDcSIfZYy4Y_tLZI_IBIxhfAsazG6oTH
"""

blocks = [
          'b1', 'b2', 'b3', 'b4'
]

gen = {
    'b1': ['d1', 'd2', 'd3'],
    'b2': ['d4', 'd5'],
    'b3': ['d6'],
    'b4': ['d7']
}

kill = {
    'b1': ['d4', 'd5', 'd6', 'd7'],
    'b2': ['d1', 'd2', 'd7'],
    'b3': ['d3'],
    'b4': ['d1', 'd4']  
}

pred = {
    'b1': [],
    'b2': ['b1', 'b3', 'b4'],
    'b3': ['b2'],
    'b4': ['b2']
}

IN = {
    key: [] for key in blocks
}
print(IN)

out = {
    key: gen[key] for key in blocks
}
print(out)

change = True
i = 0
print(f"\n\nPass: {i}\nIN:\n{IN}\n\nOUT:\n{out}")
while change:
  i += 1 
  print(f"\n\nPass: {i}\nIN:\n{IN}\n\nOUT:\n{out}")
  change = False
  for block in blocks:
    for p in pred[block]:
      IN[block] = list(
          set(IN[block]) | set(out[p])
      )
      
      oldout = out[block]
      out[block] = list(
          set(gen[block]) | (
              set(IN[block]) - set(kill[block])
          )
      )

      if out[block] != oldout:
        change = True

